- name: Restart AdGuard
  ansible.builtin.service:
    name: AdGuardHome
    state: restarted
    enabled: true

- name: Restart networking
  ansible.builtin.service:
    name: networking
    state: restarted
