apiVersion: v1
kind: Service
metadata:
  name: excalidraw-service
  namespace: excalidraw
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.234
  selector:
    app: excalidraw
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
