apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: database
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.231
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432