apiVersion: v1
kind: ConfigMap
metadata:
  name: chartdb-nginx-config
  namespace: chartdb
data:
  # Override the default Nginx configuration for ChartDB to disable IPv6
  default.conf: |
    server {
      listen 80;
      server_name _;
      location / {
        root /usr/share/nginx/html;
        index index.html;
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chartdb
  namespace: chartdb
  labels:
    app: chartdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chartdb
  template:
    metadata:
      labels:
        app: chartdb
    spec:
      containers:
        - name: chartdb
          image: ghcr.io/chartdb/chartdb:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
        - name: nginx-config
          configMap:
            name: chartdb-nginx-config