- name: Execute backups on all targets
  hosts: lxc_containers, vms
  become: yes
  vars:
    ansible_ssh_pipelining: false
  vars_files:
    - ../group_vars/secrets.yml
  tasks:
    - name: "Backup data for {{ inventory_hostname }}"
      ansible.builtin.shell:
        cmd: "restic backup {{ backup_path }} --tag {{ inventory_hostname }}"
      environment:
        RESTIC_REPOSITORY: "sftp:restic-backup@{{ ansible_controller_ip }}:/home/restic-backup/repo/{{ inventory_hostname }}"
        RESTIC_PASSWORD: "{{ restic_password }}"
        RESTIC_SFTP_COMMAND: "ssh -q -T -n -o BatchMode=yes"
      register: backup_result
      changed_when: "'files new' in backup_result.stdout"
