- name: Prepare Kubernetes node with required Python libraries
  hosts: k8s-node
  become: yes
  gather_facts: no

  tasks:
    - name: Install Kubernetes Python client library via apt
      ansible.builtin.apt:
        name: python3-kubernetes
        state: present
        update_cache: yes

- name: Create GitLab Registry Secret in Kubernetes Namespaces
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - ../group_vars/secrets.yml

  vars:
    registry_server: "registry.gitlab.luk3rr.com"
    target_namespaces: "{{ target_namespaces_str.split(',') }}"

  tasks:
    - name: Ensure target namespaces exist
      kubernetes.core.k8s:
        name: "{{ item }}"
        api_version: v1
        kind: Namespace
        state: present
      loop: "{{ target_namespaces }}"

    - name: Create or update the gitlab-registry-secret in each namespace
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: gitlab-registry-secret
            namespace: "{{ item }}"
          type: kubernetes.io/dockerconfigjson
          data:
            .dockerconfigjson: >-
              {{
                {
                  "auths": {
                    (registry_server): {
                      "username": default_admin_user,
                      "password": gitlab_deploy_token,
                      "email": registry_email
                    }
                  }
                } | to_json | b64encode
              }}
      loop: "{{ target_namespaces }}"