- name: Prepare Gitlab Runner host for fact gathering
  hosts: gitlab-runner
  become: yes
  gather_facts: no

  tasks:
    - name: Ensure lsb-release is installed
      ansible.builtin.apt:
        name: lsb-release
        state: present
        update_cache: yes

- name: Configure Gitlab Runner
  hosts: gitlab-runner
  become: yes
  gather_facts: yes
  roles:
    - gitlab-runner
  vars_files:
    - ../group_vars/secrets.yml