- name: Prepare Heimdall host for fact gathering
  hosts: heimdall
  become: yes
  gather_facts: no

  tasks:
    - name: Ensure lsb-release is installed
      ansible.builtin.apt:
        name: lsb-release
        state: present
        update_cache: yes

- name: Deploy Heimdall
  hosts: heimdall
  become: yes
  gather_facts: yes
  roles:
    - heimdall