- name: Create or Update Application Secrets in Vault KV Store
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - ../group_vars/secrets.yml

  vars:
    app_name: "{{ app_name }}"
    secrets_file_path: "{{ secrets_file_path }}"

  tasks:
    - name: "Check if kv/ secrets engine is already enabled"
      ansible.builtin.uri:
        url: "http://{{ hostvars['vault'].ansible_host }}:8200/v1/sys/mounts"
        method: GET
        headers:
          X-Vault-Token: "{{ vault_root_token }}"
        return_content: yes
      register: mounts_response
      failed_when: false
      changed_when: false

    - name: Enable kv-v2 secrets engine if not present
      ansible.builtin.uri:
        url: "http://{{ hostvars['vault'].ansible_host }}:8200/v1/sys/mounts/kv"
        method: POST
        headers:
          X-Vault-Token: "{{ vault_root_token }}"
        body_format: json
        body:
          type: kv
          options:
            version: "2"
        status_code: [ 200, 204 ]
      when: "'kv/' not in mounts_response.json"

    - name: "Write secrets for '{{ app_name }}' to Vault"
      delegate_to: "{{ hostvars['vault'].inventory_hostname }}"
      environment:
        VAULT_ADDR: "http://{{ hostvars['vault'].ansible_host }}:8200"
        VAULT_TOKEN: "{{ vault_root_token }}"
      community.hashi_vault.vault_write:
        path: "kv/data/app/{{ app_name }}"
        data:
          data: "{{ lookup('file', playbook_dir ~ '/../' ~ secrets_file_path) | from_yaml }}"
