- name: Prepare Vault host for fact gathering
  hosts: vault
  become: yes
  gather_facts: no

  tasks:
    - name: Ensure lsb-release is installed
      ansible.builtin.apt:
        name: lsb-release
        state: present
        update_cache: yes

- name: Deploy HashiCorp Vault
  hosts: vault
  become: yes
  gather_facts: yes
  roles:
    - vault