apiVersion: v1
kind: Service
metadata:
  name: chartdb-service
  namespace: chartdb
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.234
  selector:
    app: chartdb
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
