---
- name: Restart Docker
  ansible.builtin.systemd:
    name: docker
    state: restarted

- name: Restart Overleaf
  community.docker.docker_compose_v2:
    project_src: /opt/overleaf
    state: restarted
