global:
  enabled: false
  tlsDisable: true

csi:
  enabled: false

server:
  enabled: false

injector:
  enabled: true

  externalVaultAddr: https://vault.luk3rr.com

  env:
    AGENT_INJECT_VAULT_ADDR: "https://vault.luk3rr.com"
    AGENT_INJECT_VAULT_AUTH_PATH: "auth/kubernetes"

  image:
    repository: hashicorp/vault-k8s
    tag: 1.5.0
    pullPolicy: IfNotPresent

  logLevel: info

  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0

  resources:
    limits:
      cpu: 300m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

  service:
    port: 443
    type: ClusterIP

  webhook:
    certManager:
      enabled: false
    patch:
      enabled: true

  livenessProbe:
    enabled: true

  readinessProbe:
    enabled: true

  podSecurityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    runAsUser: 100

  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL